# Generated by Django 3.2.9 on 2021-11-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituce',
            fields=[
                ('id_instituce', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('kontaktni_osoba', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('heslo', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('web', models.CharField(max_length=80)),
                ('fb_stranka', models.CharField(max_length=80)),
                ('ulice', models.CharField(max_length=60)),
                ('cislo', models.IntegerField(max_length=10)),
                ('psc', models.IntegerField(max_length=10)),
                ('mesto', models.CharField(max_length=50)),
                ('ic', models.CharField(max_length=15)),
                ('dic', models.CharField(max_length=20)),
                ('popis_instituce', models.CharField(max_length=200)),
                ('email_instrukce', models.CharField(max_length=200)),
                ('email_podekovani', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id_uzivatel', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=80)),
                ('heslo', models.CharField(max_length=50)),
                ('fb_id', models.CharField(max_length=80)),
                ('google_id', models.CharField(max_length=80)),
                ('aktivni', models.BooleanField(default=False)),
                ('aktivovany', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Obdarovany',
            fields=[
                ('id_obdarovani', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('vek', models.IntegerField()),
                ('medailonek', models.CharField(max_length=150)),
                ('prani', models.CharField(max_length=100)),
                ('prani_url', models.URLField()),
                ('prani_splneno', models.BooleanField(default=None)),
                ('darce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_vanocnidarky2021.uzivatel')),
                ('instituce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_vanocnidarky2021.instituce')),
            ],
        ),
    ]
