# Generated by Django 3.2.9 on 2021-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vanocnidarky2021', '0002_auto_20211127_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituce',
            options={'verbose_name_plural': 'Instituce'},
        ),
        migrations.AlterModelOptions(
            name='obdarovany',
            options={'verbose_name_plural': 'Obdarovany'},
        ),
        migrations.AlterModelOptions(
            name='uzivatel',
            options={'verbose_name_plural': 'Uzivatel'},
        ),
        migrations.AlterField(
            model_name='instituce',
            name='cislo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='dic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='email_instrukce',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='email_podekovani',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='fb_stranka',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='popis_instituce',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='psc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='ulice',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='instituce',
            name='web',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='obdarovany',
            name='medailonek',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='obdarovany',
            name='prani_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='obdarovany',
            name='prijmeni',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='obdarovany',
            name='vek',
            field=models.IntegerField(blank=True),
        ),
    ]
